---
- name: Create virtual machine disks
  command: "qemu-img create -f qcow2 {{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ item.name }}.qcow2 {{ item.size }}G"
  args:
    creates: "{{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ item.name }}.qcow2"
  loop: "{{ lab_tripleo_vm_disks }}"
  tags:
    - lab_tripleo_images

- name: Create private provisioning network
  virt_net:
    name: openstack-private
    command: define
    xml: '{{ lookup("file", "{{ role_path }}/files/virt-net-openstack-private.xml") }}'
  tags:
    - lab_tripleo_networks

- name: Start and enable the network
  virt_net:
    name: openstack-private
    state: active
    autostart: True
  tags:
    - lab_tripleo_networks

- name: Create the Undercloud virtual machine
  command: >
    virt-install
    --name {{ lab_tripleo_openstack_release }}_{{ lab_tripleo_undercloud_name }}
    --vcpus {{ lab_tripleo_undercloud_cpus }}
    --memory {{ lab_tripleo_undercloud_memory }}
    {% if lab_tripleo_hugepages == true %}--memorybacking hugepages=on{% endif %}
    --os-variant rhel7
    --cpu host-passthrough
    --location {{ lab_tripleo_el_url }}
    --disk path={{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ lab_tripleo_undercloud_name }}.qcow2,bus=virtio,cache=none
    --network network=default
    --network network=openstack-private
    --initrd-inject {{ role_path }}/files/undercloud.cfg
    --extra-args="inst.ks=file:/undercloud.cfg{% if lab_tripleo_console %} console=tty0 console=ttyS0,115200n8{% endif %}"
  tags:
    - lab_tripleo_undercloud

- name: Create the Overcloud virtual machines
  command: >
    virt-install
    --name {{ lab_tripleo_openstack_release }}_{{ item.name }}
    --vcpus {{ lab_tripleo_overcloud_cpus }}
    --memory {{ lab_tripleo_overcloud_memory }}
    {% if lab_tripleo_hugepages == true %}--memorybacking hugepages=on{% endif %}
    --os-variant rhel7
    --cpu host-passthrough
    --import
    --disk path={{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ item.name }}.qcow2,bus=virtio,cache=none
    --network network=default
    --network network=openstack-private
    --import
  loop: "{{ lab_tripleo_vm_disks }}"
  tags:
    - lab_tripleo_overcloud
