---
- name: Create virtual machine disks
  # This creates a disk size that is 1GB more than expected for the Overcloud nodes.
  # The storage should be slightly greater than the disk size specified in the flavor
  # to avoid partitioning issues.
  command: "qemu-img create -f qcow2 {{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ item.name }}.qcow2 {{ item.size + 1 }}G"
  args:
    creates: "{{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ item.name }}.qcow2"
  with_items:
    - "{{ lab_tripleo_undercloud_node }}"
    - "{{ lab_tripleo_overcloud_nodes }}"
  when: not lab_tripleo_preprovisioned
  tags:
    - lab_tripleo_images

- name: Configure the pre-provisioned nodes password
  command: >
    virt-customize
    -a {{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_preprovisioned_image }}
    --root-password password:{{ lab_tripleo_password }}
    --uninstall cloud-init
  no_log: "{{ lab_tripleo_no_log }}"
  when: lab_tripleo_preprovisioned

- name: Configure the pre-provisioned to have their machine-id reset
  command: virt-sysprep --operations machine-id -a {{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_preprovisioned_image }}
  when: lab_tripleo_preprovisioned

- name: Copying pre-provisioned images (via Ansible)
  copy:
    src: "{{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_preprovisioned_image }}"
    dest: "{{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ item.name }}.qcow2"
    remote_src: True
  with_items:
    - "{{ lab_tripleo_undercloud_node }}"
    - "{{ lab_tripleo_overcloud_nodes }}"
  when: lab_tripleo_preprovisioned and
        (lab_tripleo_copy_method == "ansible")

- name: Copying pre-provisioned images (via qemu-img)
  command: >
    qemu-img create -f qcow2 -b
    {{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_preprovisioned_image }}
    {{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ item.name }}.qcow2
  with_items:
    - "{{ lab_tripleo_undercloud_node }}"
    - "{{ lab_tripleo_overcloud_nodes }}"
  when: lab_tripleo_preprovisioned and
        (lab_tripleo_copy_method == "qemu-img")

- name: Copying pre-provisioned images (via cp --relink)
  command: >
    cp --reflink
    {{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_preprovisioned_image }}
    {{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ item.name }}.qcow2
  with_items:
    - "{{ lab_tripleo_undercloud_node }}"
    - "{{ lab_tripleo_overcloud_nodes }}"
  when: lab_tripleo_preprovisioned and
        (lab_tripleo_copy_method == "reflink")

- name: Create private provisioning network
  virt_net:
    name: openstack-private
    command: define
    xml: '{{ lookup("file", "{{ role_path }}/files/virt-net-openstack-private.xml") }}'
  tags:
    - lab_tripleo_networks

- name: Start and enable the network
  virt_net:
    name: openstack-private
    state: active
    autostart: True
  tags:
    - lab_tripleo_networks

- name: Create the Undercloud kickstart file
  template:
    src: undercloud.cfg.j2
    dest: /tmp/lab_tripleo_undercloud.cfg
    force: True
  when: not lab_tripleo_preprovisioned
  tags:
    - template

- name: Create the Undercloud virtual machine
  command: >
    virt-install
    --name {{ lab_tripleo_undercloud_name }}.{{ lab_tripleo_openstack_release }}
    --vcpus {{ lab_tripleo_undercloud_cpus }}
    --memory {{ lab_tripleo_undercloud_memory }}
    {% if lab_tripleo_hugepages %}--memorybacking hugepages=on{% endif %}
    --os-variant rhel7.0
    {% if lab_tripleo_cpu_passthrough %}--cpu host-passthrough{% endif %}
    --disk path={{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ lab_tripleo_undercloud_name }}.qcow2,bus=virtio,cache=none
    --network network=default
    --network network=openstack-private
    {% if not lab_tripleo_preprovisioned %}
    --location {{ lab_tripleo_el_url }}
    --initrd-inject /tmp/lab_tripleo_undercloud.cfg --extra-args="inst.ks=file:/lab_tripleo_undercloud.cfg{% if lab_tripleo_console %} console=tty0 console=ttyS0,115200n8{% endif %}"
    {% endif %}
    {% if lab_tripleo_preprovisioned %}--import{% endif %}
  tags:
    - lab_tripleo_undercloud

- name: Create the Overcloud virtual machines
  command: >
    virt-install
    --name {{ item.name }}.{{ lab_tripleo_openstack_release }}
    --vcpus {{ lab_tripleo_overcloud_cpus }}
    --memory {{ lab_tripleo_overcloud_memory }}
    {% if lab_tripleo_hugepages == true %}--memorybacking hugepages=on{% endif %}
    --os-variant rhel7.0
    {% if lab_tripleo_cpu_passthrough %}--cpu host-passthrough{% endif %}
    --import
    --disk path={{ lab_tripleo_libvirt_images_location }}/{{ lab_tripleo_openstack_release }}_{{ item.name }}.qcow2,bus=virtio,cache=none
    --network network=default
    --network network=openstack-private,mac={{ item.mac }}
    --import
  loop: "{{ lab_tripleo_overcloud_nodes }}"
  tags:
    - lab_tripleo_overcloud

- name: Saving Ironic node configuration to /tmp/lab_tripleo_instackenv.*
  template:
    src: "instackenv.{{ item }}.j2"
    dest: "/tmp/lab_tripleo_instackenv.{{ item }}"
    force: True
  loop:
    - json
    - yaml
  tags:
    - instackenv
    - template
